{
    "name": "EagleWorks Export BMD Reports",
    "version": "18.0.1.0.0",
    "author": "EagleWorks GmbH",
    "license": "AGPL-3",
    "category": "Accounting/Localizations/Point of Sale",
    "website": "https://www.eagleworks.at",
    "depends": ["sale", "account_accountant"],
    "summary": "Export von Daten aus Odoo, aufbereitet den Import in BMD.",
    "description": "Export von Daten aus Odoo, aufbereitet den Import in BMD.",
    "data": [
        "security/ir.model.access.csv",
        "data/data.xml",
        "views/bmd_reports_view.xml",
        "views/res_partner.xml",
        "views/account_move_line.xml",
        "views/account_tax_views.xml",
        "views/bmd_export_history_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "post_init_hook": "post_init_hook",
}
